version: "3"
services:
  db:
    image: postgres:13.0
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - /run/desktop/mnt/host/c/Projects/data/yuimarl_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myworkdb
      POSTGRES_USER: mywork
      POSTGRES_PASSWORD: test01
    hostname: postgres
    restart: always
