apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: yuimarl
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgresql

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: yuimarl
  labels:
    app: postgresql
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: slow
  hostPath:
    #path: /data/db-pv/
    path: /run/desktop/mnt/host/c/Projects/data/yuimarl_db  # Docker for Windows
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: yuimarl
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  namespace: yuimarl
  labels:
    app: postgresql
data:
  POSTGRES_DB: ympostgresdb
  POSTGRES_USER: ympostgresadmin
  POSTGRES_PASSWORD: ympostgrespwd

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: yuimarl
  labels:
    app: postgresql
spec:
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:13.0
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: postgres-configuration
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim
