-- YM_GENERATED_ID
INSERT INTO YM_GENERATED_ID (KEY_NAME, VALUE) VALUES ('CATEGORY_NO_MAX', 13);
INSERT INTO YM_GENERATED_ID (KEY_NAME, VALUE) VALUES ('EVENT_NO_MAX', 22);
INSERT INTO YM_GENERATED_ID (KEY_NAME, VALUE) VALUES ('EVENTSET_NO_MAX', 3);
INSERT INTO YM_GENERATED_ID (KEY_NAME, VALUE) VALUES ('EVENTVIEW_NO_MAX', 1);
INSERT INTO YM_GENERATED_ID (KEY_NAME, VALUE) VALUES ('PARTY_NO_MAX', 1);
INSERT INTO YM_GENERATED_ID (KEY_NAME, VALUE) VALUES ('RELATION_NO_MAX', 20);
INSERT INTO YM_GENERATED_ID (KEY_NAME, VALUE) VALUES ('USER_NO_MAX', 5);

-- YM_USER
INSERT INTO YM_USER (USER_NO, USER_ID,  PASSWORD, PARTY,  ACCOUNT_GROUP, AUTH_MAP, DEL_FLG, AUTH_REGIST_USER, AUTH_REGIST_TIME, VERSION_NO)
VALUES (1, 'U00001', '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08', 1, 'adminGroup', '11111111111111111', '0', 1, current_timestamp, 1);

-- YM_PREFECTURE
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (1, '北海道', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (2, '青森県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (3, '岩手県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (4, '宮城県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (5, '秋田県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (6, '山形県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (7, '福島県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (8, '茨城県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (9, '栃木県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (10, '群馬県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (11, '埼玉県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (12, '千葉県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (13, '東京都', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (14, '神奈川県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (15, '新潟県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (16, '富山県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (17, '石川県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (18, '福井県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (19, '山梨県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (20, '長野県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (21, '岐阜県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (22, '静岡県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (23, '愛知県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (24, '三重県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (25, '滋賀県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (26, '京都府', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (27, '大阪府', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (28, '兵庫県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (29, '奈良県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (30, '和歌山県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (31, '鳥取県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (32, '島根県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (33, '岡山県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (34, '広島県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (35, '山口県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (36, '徳島県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (37, '香川県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (38, '愛媛県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (39, '高知県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (40, '福岡県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (41, '佐賀県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (42, '長崎県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (43, '熊本県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (44, '大分県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (45, '宮崎県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (46, '鹿児島県', '0');
INSERT INTO YM_PREFECTURE (PREFECTURE_NO, NAME, DEL_FLG) VALUES (47, '沖縄県', '0');
